FROM balenalib/%%BALENA_MACHINE_NAME%%-debian:bullseye-build as builder

WORKDIR /hello-world
RUN curl https://raw.githubusercontent.com/matt-42/lithium/master/install.sh | bash -s - 

RUN install_packages gcc cmake libboost-context-dev libboost-dev curl libpq-dev cmake

COPY /src CMakeLists.txt ./

RUN cmake -LH . && make 

FROM balenalib/%%BALENA_MACHINE_NAME%%-debian:bullseye-run

WORKDIR /hello-world

COPY --from=builder /hello-world/my_api .
COPY views ./

CMD ["./my_api"]