FROM balenalib/%%BALENA_ARCH%%-debian:latest-build

WORKDIR /hello-world

RUN install_packages gcc cmake libboost-context-dev libboost-dev curl libpq-dev cmake 
RUN curl https://raw.githubusercontent.com/matt-42/lithium/master/install.sh | bash -s -

COPY CMakeLists.txt .
COPY src/ src/
COPY views/ views/

RUN cmake -LH . && make

CMD ["./my_api"]